name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: Borales/actions-yarn@v2.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn test and lint
      run: |
        yarn test
        yarn lint
      env:
        CI: true
